import type { D1CockpitProjection } from "../../src/screens/d1_cockpit";

export const D1_PROJECTION: D1CockpitProjection = {
  preferences: {
    locale: "en",
    skin: "aurora",
    mode: "dark",
    density: "regular",
    motion: "reduced",
    diagnostics: [],
  },
  selectedLaneId: "lane-core",
  // The titlebar git block, projected from the same workspace source the
  // context dock renders: one active Lane, one worktree. `project` carries the
  // name Core published, which is also what the rail's `.wsroot` group header
  // and the picker's "In workspace" row render.
  topbarSource: {
    project: "viden",
    branch: "codex/lane-core",
    ahead: 1,
    behind: 0,
    dirty: true,
    status: "ready",
    truncated: false,
    laneWorktreeCount: 1,
  },
  contextDock: {
    source: {
      status: "ready",
      branch: "codex/lane-core",
      worktree: ".worktrees/lane-core",
      ahead: 1,
      behind: 0,
      added: 3,
      deleted: 1,
      dirty: true,
    },
    context: null,
    laneAgent: {
      laneId: "lane-core",
      workspaceId: "workspace-contract-v1",
      projectId: "project-viden",
      sessionId: "session-lane-core",
      taskId: "task-core",
      turnId: "turn-core",
    },
    provider: {
      providerId: "deepseek",
      model: "deepseek-v4-flash",
      status: "ready",
      requestCount: 4,
      errorCount: 0,
      lastLatencyMs: 80,
      averageLatencyMs: 90,
      tokensPerSecond: 30,
    },
    services: [
      {
        id: "rust-analyzer",
        kind: "lsp",
        label: "rust-analyzer",
        status: "ready",
        detailKey: null,
      },
    ],
    checklist: [
      {
        id: "check-core",
        kind: "check_run",
        label: "GUI tests",
        status: "passed",
        command: "cargo test -p viden-gui",
        path: null,
        summary: "passed",
        failingLocation: null,
        additions: null,
        deletions: null,
      },
    ],
  },
  lanes: [
    {
      id: "lane-core",
      role: "coder",
      status: "running",
      summary: "Streaming cockpit",
      branch: "codex/lane-core",
    },
  ],
  environment: {
    cwd: "/workspace/viden",
    providerId: "deepseek",
    model: "deepseek-v4-flash",
    workMode: "build",
    permissionLevel: "ask",
    tokenTotal: 1440,
    costMicroUsd: 4200,
  },
  liveWork: {
    tasks: [{ id: "task-core", title: "Freeze contract", status: "running", progress: 40 }],
    tools: [{ id: "tool-cargo", name: "cargo", inputPreview: "cargo test", state: "running" }],
    approvals: [{ id: "approval-shell", title: "Allow test", risk: "high" }],
    queuedInputs: [{ id: "queued-1", contentPreview: "continue" }],
    evidence: [{ id: "evidence-1", kind: "test", summary: "Tests passed", path: null }],
  },
  transcript: [
    { id: "tool-tool-cargo", kind: "tool", content: "cargo · cargo test" },
    { id: "stream", kind: "assistant_stream", content: "Working…" },
  ],
  workspaceEligibility: {
    isGitRepository: true,
    hasHead: true,
    canCreateLane: true,
    diagnostic: null,
  },
  starterLanePreviews: [],
  agentAdapters: [
    {
      agentId: "codex-acp",
      displayName: "Codex",
      startability: "ready",
      diagnostics: [],
      models: [],
    },
  ],
  agentSessions: [],
  composer: { editable: true, busy: true, canCancel: true, canSubmitImmediately: false },
  statusbar: {
    workMode: "build",
    permissionLevel: "ask",
    context: null,
    eventStreamPosition: 7,
    lane: { laneId: "lane-core", agentId: null, status: "running", progress: 40 },
    latency: { lastLatencyMs: 80, averageLatencyMs: 90 },
    tokens: { inputTokens: 1200, outputTokens: 240 },
    diagnosticsCount: 0,
    requests: { requestCount: 4, errorCount: 0 },
    pendingDecisionCount: 0,
  },
  permissionDock: { workMode: "build", permissionLevel: "ask", request: null },
  recovery: {
    connection: "live",
    state: "live",
    detail: null,
    hint: null,
    recoverable: false,
    businessSuccessBlocked: false,
    usedTokens: null,
    hardTokenLimit: null,
    missingCapabilities: [],
    actions: [],
  },
  unavailableFeatures: [
    { id: "diff", available: false, code: "GUI-CORE-012", message: "Diff is unavailable." },
    { id: "apply", available: false, code: "GUI-CORE-020", message: "Apply is unavailable." },
    {
      id: "recovery",
      available: false,
      code: "GUI-CORE-003",
      message: "Checkpoint capture and restore are unavailable.",
    },
  ],
};
