/**
 * Main-window interaction capture harness.
 *
 * Renders exactly one screenshot state per `?state=` value using the shipped
 * render functions only. Nothing here reimplements a control, a label, or a
 * layout: every pixel comes from `src/screens/**` and `src/components/**`, so
 * a regression in production code shows up in the capture instead of being
 * masked by a harness copy of the UI.
 *
 * Provenance of the projections:
 *
 * - `d1*`, `settings*`, `d6-*` start from `tests/support/d1_projection.ts`,
 *   the same D1 fixture the vitest suites mount.
 * - `d12-*` starts from `../gui-screen-restore/projections/d12.json`, which
 *   `tests/capture_projections.rs` generates by running the real Rust
 *   projection over the canonical `frontend-contract-v1` `merge-gate.json`
 *   fixture. It is generated output and is never hand-edited.
 * - `d2-review-*` starts from `../gui-screen-restore/projections/d2-review.json`
 *   (and `d2-review-decided.json` for the confirmed state), `d10-blind*` from
 *   `.../d10.json` — all generated by the same test from the canonical
 *   `approval-allow-deny.json` and `multi-lane.json` fixtures.
 * - `d2` starts from `.../d2.json` and `d13` from `.../d13.json`, generated by
 *   the same test from `approval-allow-deny.json` and `dag-blocker.json`.
 * - `d11` mirrors the intake fixtures in `tests/d11_intake.spec.ts`, and `d4`
 *   mirrors `tests/d4_lane_create.spec.ts`, because neither contract has a
 *   generated capture projection yet: both screens read their state from
 *   adapter-held intent results rather than from `RuntimeViewState`.
 *
 * Every hand-written value below is a *delta* on one of those sources and
 * carries a comment naming the fixture it mirrors.
 *
 * Determinism: the wall clock and `Math.random` are frozen before the first
 * render, so the elapsed-time readout in the work-status strip and any
 * id-shaped value are stable across captures. Host callbacks are stubs that
 * never resolve, so no state ever changes after the harness settles — except
 * `d6-error`, whose stub rejects with one fixed sentence on purpose.
 */

import "../../src/ui/tokens.css";
import "../../src/ui/theme.css";
import "../../src/ui/window_chrome.css";

import type { PaletteWorkspaceFiles } from "../../src/components/command_palette";
import type { Locale } from "../../src/i18n/catalog";
import type { ComposerControlIntent } from "../../src/models/composer";
import type { WorkspaceDiffProjection } from "../../src/models/diff_review";
import {
  IDLE_OPERATOR_GIT,
  type OperatorGitProjection,
} from "../../src/models/operator_git";
import type { RecentWorkResult } from "../../src/models/recent_work";
import type { PreferenceIntentOutcome } from "../../src/preferences";
import {
  renderD1Cockpit,
  type D1CockpitProjection,
  type D1IntentResult,
} from "../../src/screens/d1_cockpit";
import type { D6IntentResult, D6RecoveryProjection } from "../../src/screens/d6_recovery";
import {
  renderD11Intake,
  type D11IntakeProjection,
  type D11IntentResult,
} from "../../src/screens/d11_intake";
import {
  renderD12IntegrationGate,
  type D12IntegrationGateProjection,
  type D12IntentResult,
} from "../../src/screens/d12_integration_gate";
import {
  renderD14,
  type D14AuditProjection,
  type D14AuditTimelineProjection,
} from "../../src/screens/d14_audit_timeline";
import {
  renderD2Decisions,
  type D2DecisionsProjection,
  type D2IntentResult,
} from "../../src/screens/d2_decisions";
import {
  renderD10LaneMonitor,
  type D10LaneMonitorProjection,
} from "../../src/screens/d10_lane_monitor";
import {
  renderD13FleetWorkflow,
  type D13FleetWorkflowProjection,
} from "../../src/screens/d13_fleet_workflow";
import {
  renderD4LaneCreate,
  type D4IntentResult,
  type D4LaneCreateProjection,
  type D4StarterSeed,
} from "../../src/screens/d4_lane_create";
import {
  applyResolvedTheme,
  resolveTheme,
  type PreferenceDiagnostic,
} from "../../src/ui/theme";
import { D1_PROJECTION } from "../../tests/support/d1_projection";

/* ------------------------------------------------------------------ */
/* Determinism                                                         */
/* ------------------------------------------------------------------ */

/// Frozen wall clock. `renderWorkStatus` prints `now() - startedAt`, so an
/// unfrozen clock would make two captures of the same state differ.
const FROZEN_EPOCH_MS = Date.parse("2026-01-01T00:00:00.000Z");
Date.now = () => FROZEN_EPOCH_MS;
/// The same instant in the epoch seconds Core's recent-work DTOs carry.
const FROZEN_EPOCH = Math.floor(FROZEN_EPOCH_MS / 1000);
Math.random = () => 0;

/// A host callback that never answers. A screenshot state must not move after
/// it settles, and a never-resolving promise is the only stub that cannot
/// smuggle a state change into the capture.
const PENDING_FOREVER: Promise<never> = new Promise<never>(() => undefined);
const never = <T>(): Promise<T> => PENDING_FOREVER;

/// One macrotask, so a click's `await` chain and the following render flush
/// before the next harness step runs.
const tick = (): Promise<void> =>
  new Promise((resolve) => {
    window.setTimeout(resolve, 0);
  });

/// Waits for a node a production render is expected to produce. Bounded, so a
/// state that can no longer be reached fails visibly instead of hanging.
async function waitFor<T extends Element>(selector: string): Promise<T | null> {
  for (let attempt = 0; attempt < 60; attempt += 1) {
    const found = document.querySelector<T>(selector);
    if (found) return found;
    await tick();
  }
  return null;
}

function click(selector: string): void {
  document.querySelector<HTMLElement>(selector)?.click();
}

/* ------------------------------------------------------------------ */
/* Parameters and theme                                                */
/* ------------------------------------------------------------------ */

const params = new URLSearchParams(window.location.search);
const state = params.get("state") ?? "d1";
const locale: Locale = params.get("locale") === "zh-CN" ? "zh-CN" : "en";
const mode = params.get("mode") === "light" ? "light" : "dark";
/// Skin follows mode the way the shipped design pairs them; the harness never
/// ships a palette of its own — `resolveTheme` remains the only authority.
const skin = mode === "light" ? "ice" : "aurora";
const preferences = {
  locale,
  skin,
  mode,
  density: "regular",
  motion: "reduced",
  diagnostics: [] as PreferenceDiagnostic[],
};

document.documentElement.lang = locale;
applyResolvedTheme(document.documentElement, resolveTheme(preferences));

const root = document.querySelector<HTMLElement>("#app");
if (!root) throw new Error("capture harness: missing #app");

/* ------------------------------------------------------------------ */
/* D1 cockpit projection                                               */
/* ------------------------------------------------------------------ */

/**
 * The shared D1 fixture with the deltas the cockpit states need.
 *
 * Base: `tests/support/d1_projection.ts` (the D1 fixture the cockpit,
 * statusbar and composer-control suites all mount).
 */
function d1Base(): D1CockpitProjection {
  const base = structuredClone(D1_PROJECTION);
  return {
    ...base,
    // Delta: the harness renders the requested locale/skin/mode. The cockpit
    // reads its locale from `preferences.locale`, so the URL parameter has to
    // land here and not only on the document element.
    preferences: { ...base.preferences, locale, skin, mode },
    contextDock: {
      ...base.contextDock,
      // Delta: a Core context budget, so the dock and the statusbar's
      // `context` segment agree. Mirrors the `ContextUsageProjection` shape
      // asserted in `tests/statusbar.spec.ts`.
      context: {
        budgetId: "budget-lane-core",
        usedTokens: 42_100,
        softTokenLimit: 96_000,
        hardTokenLimit: 128_000,
        remainingTokens: 85_900,
        exceeded: false,
      },
    },
    agentAdapters: [
      {
        ...base.agentAdapters[0]!,
        // Delta: adapter model options, so the model selector shows a second
        // group. Mirrors the adapter fixture in
        // `tests/composer_controls.spec.ts`.
        models: ["gpt-5.3-codex", "gpt-5.3-codex-mini"],
      },
    ],
    statusbar: {
      ...base.statusbar,
      // Delta: the three segments the shared fixture leaves empty, so all nine
      // statusbar segments carry a fact and the pending-gate chip renders.
      // Mirrors the populated statusbar fixture in `tests/statusbar.spec.ts`.
      context: { usedTokens: 42_100, hardTokenLimit: 128_000, exceeded: false },
      diagnosticsCount: 1,
      pendingGateCount: 2,
    },
  };
}

/**
 * The pending permission ask the deny-redirect states start from.
 *
 * Delta on the shared D1 fixture, which carries no request. The shape mirrors
 * the dock fixture in `tests/permission_dock.spec.ts`, and the command mirrors
 * the design's own example (`rm -rf target/` outside the Lane allowlist).
 */
const PERMISSION_REQUEST: NonNullable<
  D1CockpitProjection["permissionDock"]["request"]
> = {
  id: "approval-shell",
  toolName: "shell",
  title: "Approve shell",
  message: "Core requests scoped permission",
  inputPreview: "rm -rf target && cargo build --release",
  isMutating: true,
  reason: "recursive delete outside the allowlist",
  risk: "high",
  target: {
    kind: "repo_path",
    display: "/workspace/viden/target",
    canonicalRef: "repo://target",
  },
  policyReasonKey: "permission.requires_approval",
  policyReasonArgs: {},
  expiresAt: 1_700_003_600,
  defaultAction: "deny",
  auditId: "audit-shell",
  blockedByPlan: false,
  actions: [
    { kind: "once", available: true, sessionId: null, paths: [], code: null },
    {
      kind: "session",
      available: true,
      sessionId: "session-lane-core",
      paths: [],
      code: null,
    },
    {
      kind: "repo_allowlist",
      available: true,
      sessionId: null,
      paths: ["/workspace/viden/apps/gui"],
      code: null,
    },
    { kind: "always", available: false, sessionId: null, paths: [], code: "GUI-CORE-003" },
    { kind: "edit", available: false, sessionId: null, paths: [], code: "GUI-CORE-003" },
    { kind: "deny", available: true, sessionId: null, paths: [], code: null },
  ],
};

/**
 * The cockpit with that ask pending in its permission dock, owned by an ACP
 * Agent.
 *
 * Delta: one `agentSessions` entry under the exact session id Core's
 * `laneAgent` fact already names, which is what makes this Lane's conversation
 * the ACP one. It is there so the deny redirect can name the agent — the
 * design's own wording — from Core's published `displayName` rather than from
 * a client guess. Mirrors the ACP session shape in `tests/d6_recovery.spec.ts`.
 */
function d1Pending(): D1CockpitProjection {
  const base = d1Base();
  return {
    ...base,
    permissionDock: { ...base.permissionDock, request: PERMISSION_REQUEST },
    agentSessions: [
      {
        sessionId: base.contextDock.laneAgent!.sessionId ?? "session-lane-core",
        laneId: "lane-core",
        agentId: "codex-acp",
        model: "gpt-5.3-codex",
        status: "waiting_approval",
        task: "Freeze contract",
        diagnostic: null,
      },
    ],
  };
}


/**
 * The pending approval with Core's structured decision context attached
 * (GUI-CORE-012).
 *
 * Delta on the canonical `structured-diff.json` fixture's `edit_file`
 * approval: the same one-file, one-hunk diff and the same `base_sha256`. The
 * tool is `edit_file` rather than the shared `shell` request, because
 * `edit_file` is one of exactly three proposals Core attaches a context to —
 * a `shell` approval carrying hunks would be a screenshot of something Core
 * never publishes.
 */
function d1DecisionContext(): D1CockpitProjection {
  const base = d1Pending();
  return {
    ...base,
    permissionDock: {
      ...base.permissionDock,
      request: {
        ...PERMISSION_REQUEST,
        id: "approval-structured-edit",
        toolName: "edit_file",
        title: "Approve edit_file",
        message: "edit_file requires approval",
        inputPreview: "path: crates/types/src/diff.rs",
        reason: "edit_file requires approval",
        risk: "medium",
        target: {
          kind: "repo_path",
          display: "crates/types/src/diff.rs",
          canonicalRef: "repo://crates/types/src/diff.rs",
        },
        auditId: "audit_approval_structured_edit",
        decisionContext: {
          diff: {
            files: [REVIEW_PAGE.entries[0]!.diff!],
            truncated: false,
            byteLimit: 65_536,
          },
          baseSha256:
            "3f79bb7b435b05321651daefd374cdc681dc06faa65e374e38337b88ca046dea",
        },
      },
    },
  };
}

/**
 * A stopped ACP session with its two Core-backed recovery actions available.
 *
 * Mirrors the `STOPPED` fixture in `tests/d6_recovery.spec.ts`: `restart`
 * carries the session id Core published and `close_lane` the lane id, which is
 * what makes the buttons operable rather than inert.
 */
const D6_STOPPED: D6RecoveryProjection = {
  connection: "live",
  state: "agent_stopped",
  detail: "ACP session failed",
  hint: "Restart the agent session or close the Lane.",
  recoverable: true,
  businessSuccessBlocked: true,
  usedTokens: null,
  hardTokenLimit: null,
  missingCapabilities: [],
  actions: [
    { kind: "reconnect", available: false, code: "GUI-CORE-003" },
    { kind: "inspect", available: true, code: "presentation_only" },
    {
      kind: "restart",
      available: true,
      code: "core_command",
      sessionId: "session-lane-core",
      laneId: "lane-core",
    },
    { kind: "close_lane", available: true, code: "core_command", laneId: "lane-core" },
    { kind: "checkpoint", available: false, code: "GUI-CORE-003" },
  ],
};

/// Core's own words for a refused recovery action. Fixed, so `d6-error`
/// captures the same sentence every time.
const D6_REJECTION = "Core rejected restart: session-lane-core is no longer published.";

interface CockpitOptions {
  projection: D1CockpitProjection;
  /** Present so the rail's gear opens the Settings overlay. */
  preferencesAvailable?: boolean;
  /** Rejects instead of hanging, for the recovery-alert state. */
  d6Rejects?: boolean;
  /** Present so the command palette's `Jump to` section resolves. */
  crossLane?: boolean;
  /** Present so the command palette's `Files` section resolves. */
  files?: boolean;
  /** Present so the titlebar selector and the rail footer open the picker. */
  projectPicker?: boolean;
  /** The `WorkspaceDiffLoaded` page the DiffReview entry points resolve to. */
  workspaceDiff?: WorkspaceDiffProjection;
  /**
   * The `OperatorGitActionFinished` answer the commit bar resolves to.
   *
   * Present makes the bar and the titlebar sync chip live; absent leaves both
   * in their unbound-host shape, which is a different capture.
   */
  operatorGit?: OperatorGitProjection;
}

function mountCockpit(options: CockpitOptions): void {
  const { projection } = options;
  renderD1Cockpit(
    root!,
    projection,
    never<D1IntentResult>,
    never<D1IntentResult>,
    never<unknown>,
    never<D6RecoveryProjection>,
    {
      // No timers: the capture must not move while the operator frames it.
      poll: false,
      showWelcome: false,
      onNavigate: () => undefined,
      sendComposerControl: (_intent: ComposerControlIntent, _laneId: string | null) =>
        never<D1IntentResult>(),
      sendD6Intent: options.d6Rejects
        ? () => Promise.reject(new Error(D6_REJECTION))
        : () => never<D6IntentResult>(),
      loadPaletteCrossLane: options.crossLane
        ? async () => PALETTE_CROSS_LANE
        : undefined,
      loadPaletteFiles: options.files ? async () => PALETTE_FILES : undefined,
      // The same read pair the shell injects: `read` answers the capability
      // and the staleness check with no Core traffic, `query` answers the
      // actual `QueryWorkspaceDiff`. Both resolve to one fixed page, so the
      // capture cannot move after it settles.
      workspaceDiff: options.workspaceDiff
        ? {
            read: async () => options.workspaceDiff!,
            query: async () => options.workspaceDiff!,
          }
        : undefined,
      // The same triple the shell injects. Every call resolves to one fixed
      // answer, so the capture cannot move after it settles — including the
      // pending states, whose answer is itself "still pending".
      operatorGit: options.operatorGit
        ? {
            read: async () => options.operatorGit!,
            run: async () => options.operatorGit!,
            poll: async () => options.operatorGit!,
          }
        : undefined,
      loadRecentWork: options.projectPicker ? async () => RECENT_WORK : undefined,
      // The chooser never resolves, so `Add directory…` cannot advance the
      // capture past the columns it is framing.
      onPickProjectFolder: options.projectPicker ? () => never<string | null>() : undefined,
      onOpenWorkspace: options.projectPicker ? () => never<void>() : undefined,
      preferences:
        options.preferencesAvailable === undefined
          ? undefined
          : {
              isAvailable: async () => options.preferencesAvailable === true,
              save: () => never<PreferenceIntentOutcome>(),
              restore: () => never<PreferenceIntentOutcome>(),
            },
    },
  );
}

/**
 * The cross-Lane gates and asks the palette reads when it opens.
 *
 * Delta on the shared fixtures: `gate-core` mirrors the merge gate in
 * `tests/d12_integration_gate.spec.ts`, and the ask mirrors the single
 * `liveWork.approvals` entry the D1 fixture already carries, so the capture
 * shows a populated `Jump to` section without inventing a decision.
 */
const PALETTE_CROSS_LANE = {
  gates: [{ gateId: "gate-core", taskId: "task-core", status: "blocked", dormant: false }],
  asks: [
    { id: "approval-shell", title: "Allow test", kind: "approval", laneId: "lane-core" },
  ],
};

/**
 * The workspace inventory Core publishes for the palette's `~` scope
 * (GUI-CORE-022).
 *
 * Delta on this repository's own tree: the paths are real Viden paths in the
 * lexicographic order Core's walk produces, and the byte sizes are fixed so two
 * captures of the same state are identical. Core owns the ordering; the harness
 * only supplies the page a real read would have returned.
 */
const PALETTE_FILES: PaletteWorkspaceFiles = {
  outcome: { state: "confirmed", reason: null },
  entries: [
    { path: "AGENTS.md", kind: "file", sizeBytes: 12_288 },
    { path: "apps", kind: "dir", sizeBytes: null },
    { path: "apps/gui/src/main.ts", kind: "file", sizeBytes: 28_672 },
    { path: "apps/tui/src/tui/jump.rs", kind: "file", sizeBytes: 11_264 },
    { path: "crates", kind: "dir", sizeBytes: null },
    { path: "crates/types/src/workspace_files.rs", kind: "file", sizeBytes: 5_632 },
  ],
  complete: true,
  loaded: true,
  pendingCommandId: null,
  capabilityAvailable: true,
};

/**
 * The Core audit page D10's event ticker renders (GUI-CORE-014).
 *
 * Delta: two projects interleaved in one newest-first page, mirroring the
 * canonical `audit-ordering.json` fixture, so the capture shows the ticker's
 * defining property — one order across projects, not a per-project list.
 */
const D10_EVENTS = {
  capabilityAvailable: true,
  loaded: true,
  outcome: { state: "confirmed", reason: null },
  rows: [
    {
      auditId: "audit_delta_review",
      timestamp: 1_700_000_200,
      projectId: "project_viden_docs",
      laneId: "lane_docs_writer",
      actorKind: "operator",
      agentId: null,
      action: "review.decided",
      objects: [],
      outcome: "success",
      args: [],
    },
    {
      auditId: "audit_charlie_revert",
      timestamp: 1_700_000_200,
      projectId: "project_viden",
      laneId: "lane_core_runtime",
      actorKind: "operator",
      agentId: null,
      action: "change.reverted",
      objects: [],
      outcome: "success",
      args: [],
    },
    {
      auditId: "audit_bravo_handoff",
      timestamp: 1_700_000_150,
      projectId: "project_viden_docs",
      laneId: "lane_docs_writer",
      actorKind: "operator",
      agentId: null,
      action: "handoff.created",
      objects: [],
      outcome: "success",
      args: [],
    },
    {
      auditId: "audit_alpha_gate",
      timestamp: 1_700_000_100,
      projectId: "project_viden",
      laneId: "lane_core_runtime",
      actorKind: "operator",
      agentId: null,
      action: "gate.decided",
      objects: [],
      outcome: "success",
      args: [],
    },
  ],
};

/**
 * The recent-work answer the picker and Welcome read.
 *
 * Delta on no fixture: `frontend-contract-v1` has no canonical recent-work
 * capture projection yet, so these mirror the shapes asserted in
 * `tests/recent_work.rs` and `tests/project_picker.spec.ts`. Timestamps are
 * offsets from the frozen clock, so the rendered ages are stable. The open
 * root appears here on purpose — the picker must drop it from Recent rather
 * than offer a switch to the project already open.
 */
const RECENT_WORK: RecentWorkResult = {
  outcome: { state: "confirmed", reason: null },
  projects: [
    {
      canonicalRoot: "/workspace/spatial-lm",
      displayName: "spatial-lm",
      lastUpdatedAt: FROZEN_EPOCH - 2 * 24 * 60 * 60,
      latestSessionId: "session-spatial",
    },
    {
      canonicalRoot: "/workspace/viden",
      displayName: "viden",
      lastUpdatedAt: FROZEN_EPOCH - 60 * 60,
      latestSessionId: "session-viden",
    },
  ],
  sessions: [],
  diagnostics: [],
  pendingCommandId: null,
  capabilityAvailable: true,
};

/* ------------------------------------------------------------------ */
/* D11 intake projection                                               */
/* ------------------------------------------------------------------ */

/**
 * A probed project waiting on its config confirmation.
 *
 * Mirrors `EMPTY_PROJECTION` in `tests/d11_intake.spec.ts` plus that suite's
 * probed-project delta (`/workspace/demo`, rust pack, credential-locked
 * provider). D11 has no generated capture projection yet, so this is the one
 * screen whose projection is written out rather than loaded.
 */
const D11_PROJECTION: D11IntakeProjection = {
  project: {
    root: "/workspace/demo",
    isGitRepository: true,
    configState: "missing",
    projectName: "demo",
    mode: "rust",
    diagnostics: [],
  },
  preview: null,
  confirmedConfig: null,
  provider: {
    providerId: "deepseek",
    model: "deepseek-chat",
    status: "credential_locked",
    warning: true,
  },
  credentialHandles: [],
  starterLanes: [],
  pendingApproval: null,
  lastError: null,
  recentWork: {
    available: true,
    code: "core_command",
    message: "Recent project and session history is served by Core.",
  },
  credentialIngress: {
    available: false,
    code: "GUI-CORE-026",
    message: "Secure credential ingress is unavailable.",
  },
  capabilities: {
    projectOnboarding: true,
    credentialHandles: true,
    laneLifecycle: true,
  },
};

/* ------------------------------------------------------------------ */
/* D12 integration gate projection                                     */
/* ------------------------------------------------------------------ */

async function d12Blocked(): Promise<D12IntegrationGateProjection> {
  // Generated by `cargo test -p viden-gui --test capture_projections -- --ignored`
  // from the canonical `merge-gate.json` fixture. Accept is unavailable with
  // `missing_evidence` and reject with `no_actor`, which is exactly the
  // blocked state this capture has to show.
  const response = await fetch("../gui-screen-restore/projections/d12.json");
  return (await response.json()) as D12IntegrationGateProjection;
}

async function d12Decidable(): Promise<D12IntegrationGateProjection> {
  const blocked = await d12Blocked();
  const detail = blocked.detail;
  if (!detail) throw new Error("capture harness: generated d12 projection has no detail");
  // Delta: the gate with its required evidence recorded and an actor Core
  // published, so `d12_accept_block` and `d12_reject_block` both return
  // `None`. Mirrors the `DECIDABLE` fixture in
  // `tests/d12_integration_gate.spec.ts`.
  const gate = {
    ...detail.gate,
    evidenceIds: [...detail.gate.requiredEvidence],
    requiresIndependentValidator: false,
    hasValidator: true,
  };
  return {
    ...blocked,
    gates: [gate],
    detail: {
      ...detail,
      gate,
      missingEvidence: [],
      // Delta: a recorded check, so the action bar sits under a real checks
      // list. Mirrors the `checks` entry in the same spec fixture.
      checks: [{ id: "check-1", name: "replay-regression", status: "passed" }],
      actions: [
        { kind: "accept", available: true, code: null },
        { kind: "reject", available: true, code: null },
      ],
    },
  };
}

/// Types a bounce reason through the real input listener, so the rendered
/// enable/disable state of the bounce control is the production rule, not a
/// harness assertion.
function fillBounceReason(text: string): void {
  const input = document.querySelector<HTMLInputElement>("[data-d12-reason]");
  if (!input) return;
  input.value = text;
  input.dispatchEvent(new Event("input", { bubbles: true }));
}


/* ------------------------------------------------------------------ */
/* D2 review and D10 lane-monitor projections                          */
/* ------------------------------------------------------------------ */

/// Core's own words for a refused review verdict. Fixed, so the rejected
/// capture shows the same sentence every time. This is the message
/// `validate_review_decider` produces when the actor is not the reviewer Lane.
const D2_REVIEW_REJECTION = "review decision requires the independent reviewer lane";

async function d2Review(): Promise<D2DecisionsProjection> {
  // Generated by `cargo test -p viden-gui --test capture_projections -- --ignored`
  // from the canonical `approval-allow-deny.json` fixture plus the contract and
  // review records listed in EVIDENCE.md, with the pending review selected.
  const response = await fetch("../gui-screen-restore/projections/d2-review.json");
  return (await response.json()) as D2DecisionsProjection;
}

async function d2ReviewBlocked(): Promise<D2DecisionsProjection> {
  const decidable = await d2Review();
  const detail = decidable.detail;
  if (!detail) throw new Error("capture harness: generated d2 review projection has no detail");
  // Delta: the availability the host projects for a review whose owner Core
  // left at the default and whose gate carries no matching validator. Mirrors
  // `d2_review_actions_fail_closed_with_a_local_code_when_no_actor_is_derivable`
  // in `tests/d2_decisions.rs`.
  return {
    ...decidable,
    detail: {
      ...detail,
      actions: detail.actions.map((action) => ({
        ...action,
        available: false,
        code: "D2-NO-REVIEWER-ACTOR",
      })),
    },
  };
}

async function d2ReviewDecided(): Promise<D2DecisionsProjection> {
  // Generated by the same capture test from the same fixture with the review
  // settled: status `accepted`, Core's fresh decision audit id, and the
  // reviewer note stored on the record. This is the queue `decide_review`
  // actually leaves behind.
  const response = await fetch("../gui-screen-restore/projections/d2-review-decided.json");
  return (await response.json()) as D2DecisionsProjection;
}

/// Mounts the review queue and drives one accept through the production
/// listener, so the captured receipt is the screen's real outcome rendering.
///
/// The projection the intent result carries is the one Core would have
/// republished for that outcome, never the pending queue with a different
/// receipt pinned to it: a confirmed verdict comes *from* `ReviewRequestUpdated`,
/// so by the time the outcome is confirmed the review is already settled. A
/// pending verdict leaves the review pending because Core has not answered yet,
/// and a rejected one leaves it pending because Core refused the command
/// outright — both of those are the real post-send state.
async function mountD2Review(outcome: D2IntentResult["outcome"]): Promise<void> {
  const pending = await d2Review();
  const settled = outcome.state === "confirmed" ? await d2ReviewDecided() : pending;
  renderD2Decisions(
    root!,
    pending,
    async () => ({
      projection: settled,
      pendingCommandId: outcome.state === "pending" ? "gui-d2-review" : null,
      outcome,
    }),
    locale,
  );
  const note = await waitFor<HTMLTextAreaElement>("[data-d2-review-feedback]");
  if (note) {
    // Typed through the real input listener, so the captured note is what the
    // production draft handling produces.
    note.value = "Replay evidence matches the recorded bindings.";
    note.dispatchEvent(new Event("input", { bubbles: true }));
  }
  click("[data-d2-action='accept_review']");
}

async function d14Audit(): Promise<D14AuditProjection> {
  // Generated by `cargo test -p viden-gui --test capture_projections -- --ignored`:
  // the real acceptance-first read over a Core `AuditPageLoaded` page built
  // from `AuditRecord::sanitized` values.
  const response = await fetch("../gui-screen-restore/projections/d14-audit.json");
  return (await response.json()) as D14AuditProjection;
}

async function d14Raw(): Promise<D14AuditTimelineProjection> {
  // Generated by the same test through `CoreClient::replay`.
  const response = await fetch("../gui-screen-restore/projections/d14-raw.json");
  return (await response.json()) as D14AuditTimelineProjection;
}

/// The audit view scoped the way D12's revert row navigates into it.
///
/// Delta: only the scope Core would have been queried with. The rows are the
/// generated page as-is; a capture must not invent records for a filter.
function d14Scoped(audit: D14AuditProjection): D14AuditProjection {
  return { ...audit, scope: { kind: "revert", id: "revert-1" } };
}

async function d2Queue(): Promise<D2DecisionsProjection> {
  // Generated by the same capture test: the full queue with all three groups
  // and the first gate approval selected, which is the state D2 opens in.
  const response = await fetch("../gui-screen-restore/projections/d2.json");
  return (await response.json()) as D2DecisionsProjection;
}

async function d2Contract(): Promise<D2DecisionsProjection> {
  const queue = await d2Queue();
  const contracts = queue.groups.find((group) => group.kind === "contract");
  const record = contracts?.items[0];
  if (!record) throw new Error("capture harness: generated d2 projection has no contract record");
  // Delta: the contract record selected, with the detail the host projects for
  // a decided contract. Mirrors
  // `d2_contract_detail_keeps_both_verdicts_visible_and_non_actionable` in
  // `tests/d2_decisions.rs`; every value below is the record's own.
  return {
    ...queue,
    selectedId: record.id,
    detail: {
      id: record.id,
      kind: "contract",
      title: record.title,
      projectId: record.projectId,
      laneId: record.laneId,
      taskId: record.taskId,
      auditId: record.auditId,
      auditScope: { kind: "contract", id: record.id },
      policyReasonKey: null,
      blockedByPlan: false,
      context: { source: "contract_summary", text: record.title, unavailable: null },
      evidence: [],
      actions: [
        {
          kind: "confirm_contract",
          available: false,
          sessionId: null,
          paths: [],
          code: "GUI-CORE-013",
        },
        {
          kind: "reject_contract",
          available: false,
          sessionId: null,
          paths: [],
          code: "GUI-CORE-013",
        },
      ],
    },
  };
}

async function d13Fleet(): Promise<D13FleetWorkflowProjection> {
  // Generated by the same capture test from the canonical `dag-blocker.json`
  // fixture plus the blocked dependency record listed in EVIDENCE.md.
  const response = await fetch("../gui-screen-restore/projections/d13.json");
  return (await response.json()) as D13FleetWorkflowProjection;
}

/// The starter-lane queue and the reviewed preview D4 renders.
///
/// Hand-written, mirroring `SEEDS` and `PREVIEW` in
/// `tests/d4_lane_create.spec.ts`: D4's state lives in the adapter's own
/// reviewed-preview slot rather than in `RuntimeViewState`, so
/// `tests/capture_projections.rs` has nothing to project it from.
const D4_SEEDS: readonly D4StarterSeed[] = [
  { laneId: "starter-coder", preset: "coder", branch: null, worktreePath: null },
  { laneId: "starter-reviewer", preset: "reviewer", branch: null, worktreePath: null },
  { laneId: "starter-tester", preset: "tester", branch: null, worktreePath: null },
];

const D4_PROJECTION: D4LaneCreateProjection = {
  availability: {
    available: true,
    capability: "runtime.starter_lane_preview",
    message: "Reviewed starter Lane creation is available.",
  },
  workMode: "build",
  canCreate: true,
  preview: {
    previewId: "preview-starter-coder",
    contentSha256: "a".repeat(64),
    owner: {
      workspaceId: "workspace-gui",
      projectId: "project-gui",
      laneId: "starter-coder",
      sessionId: "session-gui",
      taskId: null,
      turnId: "turn-gui",
    },
    lane: {
      id: "starter-coder",
      role: "coder",
      route: "built_in",
      gateStrength: "full",
      mutationPolicy: "propose_only",
      worktree: "/workspace/.worktrees/starter-coder",
      branch: "codex/starter-coder",
      target: "local",
      dataEgress: "deny",
      status: "draft",
      budget: { tokenLimit: null, costLimitMicroUsd: null, wallTimeLimitSecs: null },
      summary: "coder starter lane",
    },
    branch: "codex/starter-coder",
    worktreePath: "/workspace/.worktrees/starter-coder",
    baseRevision: "b".repeat(40),
    diagnostics: [],
  },
  receipt: null,
  pendingApproval: null,
  outcome: { state: "idle", reason: null, requiresRepreview: false },
  navigationLaneId: null,
};

async function d10Monitor(): Promise<D10LaneMonitorProjection> {
  // Generated by the same capture test from the canonical `multi-lane.json`
  // fixture, with bounded run facts recorded on its terminal lane.
  const response = await fetch("../gui-screen-restore/projections/d10.json");
  return (await response.json()) as D10LaneMonitorProjection;
}

async function d10Unobserved(): Promise<D10LaneMonitorProjection> {
  const monitor = await d10Monitor();
  // Delta: the same blind lane before Core observed any run. Absence must read
  // as absence rather than as a measured zero, which is a different Core fact.
  return {
    ...monitor,
    lanes: monitor.lanes.map((lane) =>
      lane.costMeterability === "blind" ? { ...lane, runStats: null } : lane,
    ),
  };
}

/* ------------------------------------------------------------------ */
/* DiffReview (GUI-CORE-012)                                           */
/* ------------------------------------------------------------------ */

/**
 * One `WorkspaceDiffLoaded` page.
 *
 * Delta on the canonical `structured-diff.json` extension fixture: the same
 * two entries it carries — one staged `modified` file with a real hunk, one
 * `omitted` addition whose counts stay real — and the same `truncated: true`
 * page flag, so the capture frames all three honesty rules at once. The
 * `source` block mirrors the fixture's resampled `WorkspaceSourceView`.
 */
const REVIEW_PAGE: WorkspaceDiffProjection = {
  outcome: { state: "confirmed", reason: null },
  targetLaneId: null,
  source: {
    status: "ready",
    branch: "codex/v3-core-runtime",
    worktree: "workspace/viden",
    ahead: 1,
    behind: 0,
    added: 2,
    deleted: 0,
    dirty: true,
  },
  entries: [
    {
      path: "crates/types/src/diff.rs",
      index: "modified",
      worktree: null,
      staged: true,
      diff: {
        path: "crates/types/src/diff.rs",
        oldPath: null,
        kind: "modified",
        binary: false,
        omitted: false,
        additions: 1,
        deletions: 1,
        hunks: [
          {
            oldStart: 42,
            oldLines: 3,
            newStart: 42,
            newLines: 3,
            header: "pub struct DiffDocument {",
            lines: [
              {
                kind: "context",
                content: "    pub files: Vec<DiffFile>,",
                oldLine: 42,
                newLine: 42,
              },
              {
                kind: "removed",
                content: "    pub truncated: bool,",
                oldLine: 43,
                newLine: null,
              },
              {
                kind: "added",
                content: "    pub truncated: bool, // bounded",
                oldLine: null,
                newLine: 43,
              },
              {
                kind: "context",
                content: "    pub byte_limit: u32,",
                oldLine: 44,
                newLine: 44,
              },
            ],
          },
        ],
      },
    },
    {
      path: "crates/types/tests/fixtures/frontend-contract-v1/structured-diff.json",
      index: null,
      worktree: "added",
      staged: false,
      diff: {
        path: "crates/types/tests/fixtures/frontend-contract-v1/structured-diff.json",
        oldPath: null,
        kind: "added",
        binary: false,
        // The byte bound dropped the rows and left the counts real.
        omitted: true,
        additions: 1_284,
        deletions: 0,
        hunks: [],
      },
    },
  ],
  truncated: true,
  loaded: true,
  pendingCommandId: null,
  capabilityAvailable: true,
  stale: false,
};

/// Core's own refusal text, verbatim from the canonical fixture's
/// `CommandRejected` for a denied `git_diff`.
const REVIEW_REJECTION: WorkspaceDiffProjection = {
  ...REVIEW_PAGE,
  outcome: {
    state: "rejected",
    reason:
      "permission denied\ntool: git_diff\nreason: DenyRule\nmessage: git_diff is denied by a workspace rule\nhint: grant the `git_diff` permission to read structured workspace changes",
  },
  source: null,
  entries: [],
  truncated: false,
  loaded: false,
};

/// A read Core answered over a clean working tree. The only state that may
/// render as "no changes".
const REVIEW_EMPTY: WorkspaceDiffProjection = {
  ...REVIEW_PAGE,
  entries: [],
  truncated: false,
  loaded: true,
};

/* ------------------------------------------------------------------ */
/* Operator source-control answers (runtime.operator_git)              */
/* ------------------------------------------------------------------ */

/// A Core that publishes operator git, with one owner this client may act as.
/// The base every action state below is a delta on.
const OPERATOR_GIT_READY: OperatorGitProjection = {
  ...IDLE_OPERATOR_GIT,
  capabilityAvailable: true,
  ownerAvailable: true,
};

/// The commit message the capture types, mirroring the canonical
/// `operator-git.json` fixture's own `Commit` action.
const COMMIT_MESSAGE = "feat(types): add operator git actions";

/// The `Ask` path: Core published an approval with `target.kind = "git"` for
/// the acting owner, so the dock owns the decision and the bar is inert.
const OPERATOR_GIT_AWAITING: OperatorGitProjection = {
  ...OPERATOR_GIT_READY,
  outcome: { state: "pending", reason: null },
  pendingCommandId: "gui-git-commit",
  pendingAction: "commit",
  awaitingApproval: true,
};

/// The fixture's own completed `Commit`: git's transcript verbatim, and the
/// source Core resampled *after* the effect — `ahead` up by one and the tree
/// clean, neither of which is read out of the output text.
const OPERATOR_GIT_COMPLETED: OperatorGitProjection = {
  ...OPERATOR_GIT_READY,
  outcome: { state: "confirmed", reason: null },
  result: {
    kind: "completed",
    action: "commit",
    targetLaneId: null,
    auditId: "audit_operator_git_commit",
    output:
      "[codex/v3-core-runtime 1a2b3c4] feat(types): add operator git actions\n 1 file changed, 2 insertions(+)",
    truncated: false,
    source: {
      status: "ready",
      branch: "codex/v3-core-runtime",
      worktree: "workspace/viden",
      ahead: 2,
      behind: 0,
      added: 0,
      deleted: 0,
      dirty: false,
    },
    failureClass: null,
    detail: null,
  },
};

/// The fixture's own failed `Push`: the effect was attempted after the gate
/// granted it, so this is an outcome and never a denial.
const OPERATOR_GIT_NO_UPSTREAM: OperatorGitProjection = {
  ...OPERATOR_GIT_READY,
  outcome: { state: "confirmed", reason: null },
  result: {
    kind: "failed",
    action: "push",
    targetLaneId: null,
    auditId: "audit_operator_git_push",
    output: null,
    truncated: false,
    source: null,
    failureClass: "no_upstream",
    detail: "the current branch has no upstream branch; push with set_upstream to create one",
  },
};

/// The fixture's own refused `Stage`: a pre-effect `CommandRejected`, carried
/// verbatim. Nothing ran, so there is no outcome beside it.
const OPERATOR_GIT_REJECTED: OperatorGitProjection = {
  ...OPERATOR_GIT_READY,
  outcome: {
    state: "rejected",
    reason:
      "permission denied\ntool: git_add\nreason: DenyRule\nmessage: git_add is denied by a workspace rule\nhint: grant the `git_add` permission to run source-control actions from this client",
  },
};

/// Types the commit message through the production input listener, the way an
/// operator does, so the capture frames the bar's real enabled state.
async function typeCommitMessage(message: string): Promise<void> {
  const input = await waitFor<HTMLInputElement>("[data-review-commit-message]");
  if (input) {
    // Typed through the real input listener, so the captured bar is in the
    // state production puts it in rather than one the harness set by hand.
    input.value = message;
    input.dispatchEvent(new Event("input", { bubbles: true }));
  }
  await tick();
}

/// Opens DiffReview from the titlebar's changes marker, the way an operator
/// does, rather than by mounting the screen directly.
async function openReview(
  page: WorkspaceDiffProjection,
  // The shell always binds the action port, so every capture does too: an
  // inert bar is what an *unbound host* shows, which no operator ever sees.
  operatorGit: OperatorGitProjection = OPERATOR_GIT_READY,
): Promise<void> {
  mountCockpit({
    projection: d1Base(),
    preferencesAvailable: true,
    workspaceDiff: page,
    operatorGit,
  });
  await waitFor("[data-topbar-review]:not([disabled])");
  click("[data-topbar-review]");
  // The view mounts in its pending state first and fills when the query
  // resolves, so waiting for the container alone would frame an empty tree.
  await waitFor("[data-diff-review]");
  if (page.entries.length > 0) await waitFor(".ftrow");
  else await waitFor("[data-review-state]");
}

/* ------------------------------------------------------------------ */
/* States                                                              */
/* ------------------------------------------------------------------ */

async function renderState(): Promise<void> {
  switch (state) {
    case "d1": {
      mountCockpit({ projection: d1Base(), preferencesAvailable: true });
      return;
    }

    case "d1-mode-menu": {
      mountCockpit({ projection: d1Base(), preferencesAvailable: true });
      click("[data-control-toggle='work_mode']");
      await waitFor("[data-control-popover='work_mode']");
      return;
    }

    case "d1-model-menu": {
      mountCockpit({ projection: d1Base(), preferencesAvailable: true });
      click("[data-control-toggle='model']");
      await waitFor("[data-control-popover='model']");
      return;
    }

    case "lane-rail": {
      // The rail auto-hides, so the capture pins it open. It must show the
      // one `.wsroot` project group Core supervises, its Lanes nested beneath,
      // and the `＋ Add project…` footer — with no fabricated second group and
      // no "Global" section.
      mountCockpit({
        projection: d1Base(),
        preferencesAvailable: true,
        projectPicker: true,
      });
      click("[data-lanes-toggle]");
      await waitFor("#d1-lane-rail[data-open='true']");
      await waitFor("[data-add-project]");
      return;
    }

    case "project-picker": {
      // Opened from the titlebar. The capture must show all three columns at
      // once: the one real Add action beside the two disabled rows naming
      // GUI-CORE-023, the single "In workspace" row for the project Core
      // actually supervises, and one Recent row.
      mountCockpit({
        projection: d1Base(),
        preferencesAvailable: true,
        projectPicker: true,
      });
      click("[data-project-selector]");
      await waitFor("[data-project-picker]");
      await waitFor("[data-picker-recent='/workspace/spatial-lm']");
      return;
    }

    case "project-switch-confirm": {
      // The guarded step: opening a project replaces the workspace, so the
      // confirmation names the running Lanes and Agent sessions it tears down
      // before anything is opened.
      mountCockpit({
        projection: d1Base(),
        preferencesAvailable: true,
        projectPicker: true,
      });
      click("[data-project-selector]");
      await waitFor("[data-picker-recent='/workspace/spatial-lm']");
      click("[data-picker-recent='/workspace/spatial-lm']");
      await waitFor("[data-picker-confirm]");
      return;
    }

    case "palette": {
      // The palette opens on an empty query on purpose: every section the
      // design draws (Actions, Jump to, Settings, Files) is visible at once,
      // which a filtered query would collapse to a single group.
      mountCockpit({
        projection: d1Base(),
        preferencesAvailable: true,
        crossLane: true,
        files: true,
      });
      click("[data-command-palette-toggle]");
      await waitFor("[data-command-palette]");
      // The cross-Lane read resolves after the overlay mounts; wait for the
      // gate row so the capture never freezes on the pending note.
      await waitFor("[data-palette-row][data-palette-item-id='gate:gate-core']");
      // The inventory read resolves independently; wait for a real path row so
      // the capture never freezes on the loading row.
      await waitFor("[data-palette-row][data-palette-item-id='file:AGENTS.md']");
      return;
    }

    case "palette-files": {
      // The `~` scope alone (GUI-CORE-022): the palette pre-scoped to files, so
      // the capture frames the Core-published inventory rather than the four
      // sections at once.
      mountCockpit({
        projection: d1Base(),
        preferencesAvailable: true,
        crossLane: true,
        files: true,
      });
      click("[data-command-palette-toggle]");
      await waitFor("[data-command-palette]");
      await waitFor("[data-palette-row][data-palette-item-id='file:AGENTS.md']");
      const field = document.querySelector<HTMLInputElement>("[data-palette-input]");
      if (field) {
        field.value = "~";
        field.dispatchEvent(new Event("input", { bubbles: true }));
      }
      await tick();
      return;
    }

    case "settings": {
      mountCockpit({ projection: d1Base(), preferencesAvailable: true });
      click("[data-settings-toggle]");
      await waitFor("[data-settings-panel]");
      // A draft, so the panel captures the dirty state: Cancel and Save both
      // become enabled only once an axis actually changed.
      click("[data-settings-option='density:comfy']");
      await waitFor("[data-settings-panel] [data-settings-option='density:comfy'][aria-checked='true']");
      // The panel is taller than one viewport now that the two Core-command
      // sections lead it, and the remount focuses the drafted option, which
      // scrolls the Provider and Permissions cards out of frame. The capture
      // is anchored to the panel's own top; the draft still proves itself
      // through the sticky Cancel/Save footer.
      document.querySelector("[data-settings-panel]")!.scrollTop = 0;
      await tick();
      return;
    }

    case "permission-ask": {
      // The dock as Core publishes it, before any verdict: the baseline the
      // redirect state is read against.
      mountCockpit({ projection: d1Pending(), preferencesAvailable: true });
      await waitFor("[data-permission-dock]");
      return;
    }

    case "permission-deny-redirect": {
      // The design's post-deny composer. `sendPermission` never resolves, so
      // the capture proves the point precisely: the prompt switches when the
      // deny is *dispatched*, claiming nothing about Core's answer.
      mountCockpit({ projection: d1Pending(), preferencesAvailable: true });
      await waitFor("[data-permission-dock]");
      click("[data-permission-action='deny']");
      await tick();
      return;
    }

    case "review": {
      // The registered DiffReview family over one Core page: the file tree
      // with its staged ✓ and per-file counts, the unified body, the page's
      // truncation banner, and the commit bar disabled under GUI-CORE-020.
      await openReview(REVIEW_PAGE);
      return;
    }

    case "review-omitted": {
      // The second entry selected, so the capture frames the "rows not shown"
      // note beside its real counts — the one rule a screenshot of the first
      // file cannot show.
      await openReview(REVIEW_PAGE);
      click("[data-path='crates/types/tests/fixtures/frontend-contract-v1/structured-diff.json']");
      await waitFor("[data-diff-note='omitted']");
      return;
    }

    case "review-rejected": {
      // Core's refusal, rendered verbatim in a `role=alert`. Never an empty
      // tree, which would read as a clean workspace.
      await openReview(REVIEW_REJECTION);
      await waitFor("[data-review-state='rejected']");
      return;
    }

    case "review-empty": {
      // The only state that may say "no changes": Core answered, with zero
      // entries.
      await openReview(REVIEW_EMPTY);
      await waitFor("[data-review-state='empty']");
      return;
    }

    case "review-commit": {
      // The commit bar live: a typed message, the three actions enabled, and
      // every file row carrying its stage/unstage toggle beside Core's own
      // staged mark.
      await openReview(REVIEW_PAGE, OPERATOR_GIT_READY);
      await typeCommitMessage(COMMIT_MESSAGE);
      await waitFor("[data-review-action='commit']:not([disabled])");
      return;
    }

    case "review-commit-pending-approval": {
      // The `Ask` path. The approval itself is the permission dock's; the bar
      // only says the decision is out and stays inert until it is answered.
      await openReview(REVIEW_PAGE, OPERATOR_GIT_AWAITING);
      await typeCommitMessage(COMMIT_MESSAGE);
      await waitFor("[data-review-action-state='awaiting_approval']");
      return;
    }

    case "review-commit-completed": {
      // The success line reads the resampled branch, ahead, behind, and clean
      // tree Core put on the outcome — never the transcript below it, which is
      // collapsed display text.
      await openReview(REVIEW_PAGE, OPERATOR_GIT_COMPLETED);
      await waitFor("[data-review-action-state='completed']");
      return;
    }

    case "review-push-no-upstream": {
      // A failure *after* the gate granted the action, with the recovery the
      // contract names for the class: resend the push with `set_upstream`.
      await openReview(REVIEW_PAGE, OPERATOR_GIT_NO_UPSTREAM);
      await waitFor("[data-review-recovery='set_upstream']");
      return;
    }

    case "review-rejected-action": {
      // A pre-effect refusal, Core's words unedited. Deliberately captured
      // beside `review-push-no-upstream`: the two must never read alike.
      await openReview(REVIEW_PAGE, OPERATOR_GIT_REJECTED);
      await waitFor("[data-review-action-state='rejected']");
      return;
    }

    case "approval-hunks": {
      // The D1 permission dock rendering `decision_context` as hunk rows, with
      // the preimage note. GUI-CORE-012's unavailable marker is gone here
      // because Core published the rows.
      mountCockpit({ projection: d1DecisionContext(), preferencesAvailable: true });
      await waitFor("[data-decision-context]");
      return;
    }

    case "settings-unavailable": {
      // Core's handshake without `ui.preference_persistence`: the panel opens
      // read-only and states the missing capability instead of hiding.
      mountCockpit({ projection: d1Base(), preferencesAvailable: false });
      click("[data-settings-toggle]");
      await waitFor("[data-settings-unavailable]");
      return;
    }

    case "d6-actions": {
      mountCockpit({
        projection: { ...d1Base(), recovery: D6_STOPPED },
        preferencesAvailable: true,
      });
      await waitFor("[data-d6-action='inspect']");
      // `inspect` is presentation-only: it expands facts the projection
      // already carries, so expanding it changes no Core state.
      click("[data-d6-action='inspect']");
      await waitFor("[data-d6-inspect]");
      return;
    }

    case "d6-error": {
      mountCockpit({
        projection: { ...d1Base(), recovery: D6_STOPPED },
        preferencesAvailable: true,
        d6Rejects: true,
      });
      await waitFor("[data-d6-action='restart']");
      click("[data-d6-action='restart']");
      await waitFor("[data-d6-error]");
      return;
    }

    case "d12-actions": {
      renderD12IntegrationGate(
        root!,
        await d12Decidable(),
        locale,
        () => undefined,
        never<D12IntentResult>,
      );
      fillBounceReason("Cancel window regressed; revalidate on the origin Lane.");
      return;
    }

    case "d12-blocked": {
      renderD12IntegrationGate(
        root!,
        await d12Blocked(),
        locale,
        () => undefined,
        never<D12IntentResult>,
      );
      return;
    }

    case "d11": {
      renderD11Intake(
        root!,
        D11_PROJECTION,
        never<D11IntentResult>,
        locale,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        // The same frozen inventory the Welcome capture uses; Date.now is
        // already frozen above, so the relative ages stay deterministic.
        { load: async () => RECENT_WORK },
      );
      return;
    }

    case "d11-recent": {
      // The same intake screen scrolled to its history panel, proving the
      // Core `QueryRecentWork` rows replaced the old static unavailability
      // sentence. The rows load in a microtask, so the capture waits for one.
      renderD11Intake(
        root!,
        D11_PROJECTION,
        never<D11IntentResult>,
        locale,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        { load: async () => RECENT_WORK },
      );
      const row = await waitFor("[data-recent-project]");
      row?.scrollIntoView({ block: "center" });
      return;
    }

    case "d2-review-pending": {
      // The verdict left in flight: the host sent `DecideReview` and Core has
      // not published `ReviewRequestUpdated` yet, so the receipt says pending
      // and never claims a decision was recorded.
      await mountD2Review({ state: "pending", reason: null });
      await waitFor("[data-d2-outcome='pending']");
      return;
    }

    case "d2-review-confirmed": {
      await mountD2Review({ state: "confirmed", reason: null });
      await waitFor("[data-d2-outcome='confirmed']");
      return;
    }

    case "d2-review-rejected": {
      // Core's own refusal sentence, rendered verbatim.
      await mountD2Review({ state: "rejected", reason: D2_REVIEW_REJECTION });
      await waitFor("[data-d2-outcome='rejected']");
      return;
    }

    case "d2-review-blocked": {
      // A pending review Core published without an independent reviewer
      // identity: both verdicts stay disabled and name the local reason.
      renderD2Decisions(root!, await d2ReviewBlocked(), never<D2IntentResult>, locale);
      await waitFor("[data-d2-unavailable='D2-NO-REVIEWER-ACTOR']");
      return;
    }

    case "d2": {
      // The queue as D2 opens: gate approvals, review requests, and the
      // contract group, with the first gate approval selected. Both contract
      // verdicts render disabled and named by GUI-CORE-013, because every
      // `ContractRecord` schema 1 publishes is already decided.
      renderD2Decisions(root!, await d2Queue(), never<D2IntentResult>, locale);
      await waitFor("[data-d2-group='contract']");
      return;
    }

    case "d2-contract": {
      // The contract record selected. Core has already decided it — schema 1
      // publishes no pending contract — and refuses a second decision on an id
      // it holds, so both verdicts render visible, disabled, and named by
      // GUI-CORE-013, with the reason spelled out once below the bar.
      renderD2Decisions(root!, await d2Contract(), never<D2IntentResult>, locale);
      await waitFor("[data-d2-action-code='GUI-CORE-013']");
      return;
    }

    case "d4": {
      // The reviewed starter-lane wizard on its review step, so the capture
      // shows the resolved route, gate strength, mutation policy, target,
      // budget, and worktree exactly as Core's preview published them — the
      // screen edits none of them.
      renderD4LaneCreate(
        root!,
        { projection: D4_PROJECTION, pendingCommandId: null, pendingIntent: null },
        never<D4IntentResult>,
        never<D4IntentResult>,
        locale,
        {
          queue: D4_SEEDS,
          queueIndex: 0,
          completedLaneIds: [],
          onCancel: () => undefined,
          onNavigateToD1: () => undefined,
        },
      );
      click('[data-d4-step="3"]');
      await waitFor("[data-resolved-route]");
      return;
    }

    case "d13": {
      // The fleet view: one Core workflow DAG with a blocked node, showing the
      // dependency Core recorded as the blocker rather than a status the
      // client inferred from ordering.
      renderD13FleetWorkflow(root!, await d13Fleet(), locale);
      await waitFor("[data-d13-blocked]");
      return;
    }

    case "d10-blind": {
      // The generated monitor: one cost-blind terminal lane carrying the four
      // bounded run facts Core recorded, beside a metered ACP lane that carries
      // none of them.
      renderD10LaneMonitor(root!, await d10Monitor(), locale, () => undefined);
      await waitFor("[data-d10-meterability='blind']");
      return;
    }

    case "d10-ticker": {
      // The event ticker (GUI-CORE-014): one bounded newest-first page of the
      // Core audit timeline, with two projects interleaved so the capture shows
      // the property that matters — one order across projects, not a
      // per-project list.
      const monitor = renderD10LaneMonitor(
        root!,
        await d10Monitor(),
        locale,
        () => undefined,
      );
      monitor.applyEvents(D10_EVENTS);
      await waitFor("[data-d10-event]");
      return;
    }

    case "d14-audit": {
      const audit = await d14Audit();
      const raw = await d14Raw();
      renderD14(root!, audit, locale, {
        queryAudit: async () => audit,
        loadOlderAudit: async () => audit,
        loadRaw: async () => raw,
      });
      await waitFor("[data-d14-audit-id]");
      return;
    }

    case "d14-audit-scoped": {
      // What D12's revert row opens: the same read with Core's object filter,
      // and the removable scope chip that re-queries unscoped.
      const audit = d14Scoped(await d14Audit());
      const raw = await d14Raw();
      renderD14(root!, audit, locale, {
        queryAudit: async () => audit,
        loadOlderAudit: async () => audit,
        loadRaw: async () => raw,
      });
      await waitFor("[data-d14-scope-clear]");
      return;
    }

    case "d14-raw-fallback": {
      // A Core that published no `runtime.audit`: D14 opens in raw mode, names
      // the capability, disables the audit toggle, and sends no audit command.
      const raw = await d14Raw();
      const unavailable: D14AuditProjection = {
        ...(await d14Audit()),
        rows: [],
        loaded: false,
        capabilityAvailable: false,
        outcome: { state: "idle", reason: null },
      };
      renderD14(
        root!,
        unavailable,
        locale,
        {
          queryAudit: async () => unavailable,
          loadOlderAudit: async () => unavailable,
          loadRaw: async () => raw,
        },
        raw,
      );
      await waitFor("[data-d14-capability-note]");
      return;
    }

    case "d10-blind-unobserved": {
      renderD10LaneMonitor(root!, await d10Unobserved(), locale, () => undefined);
      await waitFor("[data-d10-run-stats='none']");
      return;
    }

    default: {
      root!.textContent = `unknown state ${state}`;
    }
  }
}

await renderState();
// The operator's capture signal: present only after the state has settled.
document.documentElement.dataset.captureReady = state;
